// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/app_info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var app_info_default = defineTool({
  name: "app_info",
  title: "About PoortLink",
  description: "Return a brief description of the PoortLink / TukConnect platform, its brands and its capabilities.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: [
          "PoortLink is the operational layer for South African minibus taxi infrastructure.",
          "Brands: MojaRide (consumer hailing), PoortLink (operator tools), TukConnect (infrastructure).",
          "Capabilities: loading-zone queues, driver reputation & AARTO mapping, dashcam / AI incident monitoring,",
          "SASSA discount verification, digital fare collection (Yoco), Drive-to-Own program, and DOT compliance tooling.",
          "Focus area: Eersterust, Tshwane. Cross-border expansion in progress (eSwatini)."
        ].join(" ")
      }
    ]
  })
});

// src/lib/mcp/tools/list_loading_zones.ts
import { createClient } from "npm:@supabase/supabase-js@^2.50.5";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var list_loading_zones_default = defineTool2({
  name: "list_loading_zones",
  title: "List loading zones",
  description: "List active taxi loading zones (pickup areas) with location, radius, marshal status, and operating hours.",
  inputSchema: {
    municipality: z.string().optional().describe("Optional filter: municipality name (e.g. 'Tshwane')."),
    limit: z.number().int().optional().describe("Maximum number of zones to return. Default 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ municipality, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("loading_zones").select(
      "id,zone_name,zone_type,address,municipality,ward,latitude,longitude,radius_meters,has_marshal,operating_hours,is_active"
    ).eq("is_active", true).limit(limit ?? 50);
    if (municipality) q = q.ilike("municipality", `%${municipality}%`);
    const { data, error } = await q;
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { zones: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list_drive_to_own_programs.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.50.5";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_drive_to_own_programs_default = defineTool3({
  name: "list_drive_to_own_programs",
  title: "List Drive-to-Own programs",
  description: "List the active Drive-to-Own program tiers with eligibility thresholds, timelines and graduation bonuses.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("drive_to_own_programs").select("*").eq("is_active", true).order("min_reputation_score", { ascending: true });
    if (error)
      return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { programs: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "poortlink-mcp",
  title: "PoortLink MCP",
  version: "0.1.0",
  instructions: "Tools for the PoortLink / MojaRide / TukConnect taxi platform. Use `app_info` for an overview, `list_loading_zones` to discover pickup zones (optionally filter by municipality), and `list_drive_to_own_programs` to inspect Drive-to-Own tier eligibility.",
  tools: [app_info_default, list_loading_zones_default, list_drive_to_own_programs_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
